"""
Step 3.10 - Paraphrase Routing Stability
==========================================
Phase 3 robustness layer (additive, post-baseline)

Tests how stable the keyword-based router (route_question in
step_3_4_evaluation.py) is under semantic paraphrasing of the input
question. A representative sample of N_SAMPLE queries is stratified
across the three benchmark categories (factual-lookup, multi-hop-is,
comparative); each query is paraphrased N_PARAPHRASES times by
Claude Haiku 4.5 with temperature 0, then routed.

routing_stable = (original_template == paraphrase_template).

Inputs (read-only):
    data/evaluation_results_graph-rag_*.json
    step_3_4_evaluation.route_question
    config.py

Outputs:
    results/step_3_10_paraphrase_routing_per_query.csv
    results/step_3_10_routing_stability_summary.csv

Paraphrase model: Anthropic Claude Sonnet 4.6 (cross-model: production
RAG uses Haiku 4.5; paraphrases generated by Sonnet 4.6 to mitigate
self-enhancement bias, in line with Zheng et al. 2023 LLM-as-Judge
recommendations). The paraphrase model is recorded in the summary CSV
(`paraphrase_model`) for traceability.

Cost rough estimate: 20 queries * 1 Sonnet 4.6 call returning 3
paraphrases is ~ 0.10 USD and takes ~ 2-3 min.
"""

from __future__ import annotations

import json
import logging
import random
import re
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
RESULTS_DIR = BASE_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

OUT_PER_QUERY = RESULTS_DIR / "step_3_10_paraphrase_routing_per_query.csv"
OUT_SUMMARY = RESULTS_DIR / "step_3_10_routing_stability_summary.csv"

N_SAMPLE = 20
N_PARAPHRASES = 3
PARAPHRASE_MODEL = "claude-sonnet-4-6"
PARAPHRASE_TEMPERATURE = 0.0
MAX_OUTPUT_TOKENS = 350
SAMPLING_SEED = 42
CATEGORY_TARGETS: dict[str, int] = {
    "factual-lookup": 7,
    "multi-hop-is": 7,
    "comparative": 6,
}
STABILITY_MIN_PCT = 60.0

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger(__name__)


def _latest_graph_rag_file() -> Path:
    candidates = sorted(DATA_DIR.glob("evaluation_results_graph-rag_*.json"))
    if not candidates:
        raise FileNotFoundError("No graph-rag evaluation result found in data/")
    return candidates[-1]


def _stratified_sample(entries: list[dict], targets: dict[str, int], seed: int) -> list[dict]:
    rng = random.Random(seed)
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_cat[str(e.get("category", "unknown"))].append(e)
    picked: list[dict] = []
    for category, n in targets.items():
        pool = by_cat.get(category, [])
        rng.shuffle(pool)
        picked.extend(pool[:n])
    return picked


def _build_paraphrase_prompt(question: str, n: int) -> str:
    return (
        f"Paraphrase the following question {n} times preserving its exact meaning. "
        "Use synonyms, sentence reordering and equivalent phrasings. "
        "Keep the technical vocabulary intact (article numbers, standard codes, "
        "scenario labels). Return ONLY a JSON list of "
        f"{n} strings, nothing else.\n\n"
        f"Question: {question}"
    )


def _parse_paraphrases(raw: str, n_expected: int) -> list[str]:
    match = re.search(r"\[\s*\"", raw)
    if match is None:
        return []
    start = match.start()
    depth = 0
    end = start
    for i in range(start, len(raw)):
        ch = raw[i]
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    snippet = raw[start:end]
    try:
        items = json.loads(snippet)
    except json.JSONDecodeError:
        return []
    out = [str(s).strip() for s in items if isinstance(s, str) and s.strip()]
    return out[:n_expected]


def main() -> None:
    from config import ANTHROPIC_API_KEY
    from step_3_4_evaluation import route_question

    try:
        from anthropic import Anthropic
    except ImportError as exc:
        logger.error("anthropic SDK not installed: %s", exc)
        return

    path = _latest_graph_rag_file()
    logger.info(
        "Step 3.10 starting: paraphrase routing stability on %d queries x %d paraphrases (%s)",
        N_SAMPLE, N_PARAPHRASES, path.name,
    )

    with path.open("r", encoding="utf-8") as fh:
        entries = json.load(fh)

    picked = _stratified_sample(entries, CATEGORY_TARGETS, SAMPLING_SEED)
    if len(picked) != N_SAMPLE:
        logger.warning("Stratified sample produced %d items, expected %d", len(picked), N_SAMPLE)

    client = Anthropic(api_key=ANTHROPIC_API_KEY)
    rows: list[dict] = []
    t0 = time.time()

    for idx, entry in enumerate(picked, start=1):
        qid = str(entry.get("question_id", ""))
        original = str(entry.get("nl_question", ""))
        original_tpl = route_question(original)

        prompt = _build_paraphrase_prompt(original, N_PARAPHRASES)
        try:
            message = client.messages.create(
                model=PARAPHRASE_MODEL,
                max_tokens=MAX_OUTPUT_TOKENS,
                temperature=PARAPHRASE_TEMPERATURE,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = "".join(b.text for b in message.content if hasattr(b, "text"))
            paraphrases = _parse_paraphrases(raw, N_PARAPHRASES)
        except Exception as exc:
            logger.warning("Paraphrase call failed for %s: %s", qid, exc)
            paraphrases = []

        if not paraphrases:
            logger.warning("No paraphrases parsed for %s; recording UNPARAPHRASED rows", qid)
            for k in range(N_PARAPHRASES):
                rows.append({
                    "question_id": qid,
                    "category": entry.get("category", ""),
                    "paraphrase_idx": k + 1,
                    "original_question": original,
                    "paraphrased_question": "",
                    "original_template": original_tpl,
                    "paraphrase_template": "PARAPHRASE_GENERATION_FAILED",
                    "routing_stable": False,
                })
            continue

        for k, para in enumerate(paraphrases, start=1):
            para_tpl = route_question(para)
            rows.append({
                "question_id": qid,
                "category": entry.get("category", ""),
                "paraphrase_idx": k,
                "original_question": original,
                "paraphrased_question": para,
                "original_template": original_tpl,
                "paraphrase_template": para_tpl,
                "routing_stable": original_tpl == para_tpl,
            })

        if idx % 5 == 0 or idx == len(picked):
            elapsed = time.time() - t0
            logger.info("  paraphrased %d/%d queries (%.1fs elapsed)", idx, len(picked), elapsed)

    df = pd.DataFrame(rows)
    df.to_csv(OUT_PER_QUERY, index=False)
    logger.info("Wrote %s (%d rows)", OUT_PER_QUERY.name, len(df))

    stability_pct = round(100.0 * df["routing_stable"].mean(), 2) if len(df) else 0.0

    per_template = (
        df.groupby("original_template")["routing_stable"]
        .agg(["sum", "count"])
        .reset_index()
        .assign(stable_pct=lambda x: (100.0 * x["sum"] / x["count"]).round(1))
        .sort_values("stable_pct", ascending=False)
    )
    most_robust = per_template.head(2)
    least_robust = per_template.tail(2)

    def _fmt(sub: pd.DataFrame) -> str:
        return ", ".join(
            f"{r['original_template']} ({r['stable_pct']:.0f}%, n={int(r['count'])})"
            for _, r in sub.iterrows()
        )

    summary_rows = [
        {"metric": "n_queries_tested", "value": int(len(picked))},
        {"metric": "n_paraphrases_total", "value": int(len(df))},
        {"metric": "routing_stability_pct", "value": stability_pct},
        {"metric": "templates_most_robust", "value": _fmt(most_robust)},
        {"metric": "templates_least_robust", "value": _fmt(least_robust)},
        {"metric": "paraphrase_model", "value": PARAPHRASE_MODEL},
    ]
    df_summary = pd.DataFrame(summary_rows)
    df_summary.to_csv(OUT_SUMMARY, index=False)
    logger.info("Wrote %s (%d rows)", OUT_SUMMARY.name, len(df_summary))

    logger.info("=" * 70)
    logger.info(
        "  Routing stability under paraphrasing: %.1f%% (%d paraphrases over %d source queries)",
        stability_pct, len(df), len(picked),
    )
    logger.info("  Robust:  %s", _fmt(most_robust))
    logger.info("  Fragile: %s", _fmt(least_robust))
    logger.info("=" * 70)
    if stability_pct < STABILITY_MIN_PCT:
        logger.warning(
            "Routing stability %.1f%% below %.0f%% sanity bound; the keyword matcher "
            "may be too fragile to paraphrasing",
            stability_pct, STABILITY_MIN_PCT,
        )


if __name__ == "__main__":
    main()
